
package com.acvitech.spa4j.jfx;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import com.acvitech.spa4j.support.ConfigManager;

/**
 *
 * @author avikarz
 */
public class BrowseJFXDialog extends javax.swing.JDialog {

    /**
     * Creates new form LauncherDialog
     * @param parent
     * @param modal
     */
    public BrowseJFXDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fileLocation.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent arg0) {
                performTextChange();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                performTextChange();
            }

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                performTextChange();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        labelWithText = new javax.swing.JLabel();
        labelWithLink = new javax.swing.JLabel();
        lowerPanel = new javax.swing.JPanel();
        specifyOjfxLabel = new javax.swing.JLabel();
        fileLocation = new javax.swing.JTextField();
        message = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        browseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Missing/Unconfigured OpenJFX");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon(getClass().getResource(ConfigManager.getApplicationIconURI())).getImage());
        setIconImages(null);
        setName("LauncherDialog"); // NOI18N

        upperPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelWithText.setText("Please note that your JDK doesn't have an embeded JavaFX runtime which is required for running this application.");

        labelWithLink.setText("<HTML>Download JavaFX from <FONT color=\"#000099\"><U>https://openjfx.io/</U></FONT> for your machine, if you don't have it already</HTML>");
        labelWithLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelWithLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkClickedForOpenJFX(evt);
            }
        });

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelWithText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelWithLink))
                .addContainerGap())
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWithText)
                .addGap(18, 18, 18)
                .addComponent(labelWithLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        labelWithLink.getAccessibleContext().setAccessibleName("<HTML>Download OpenJFX from<FONT color=\\\"#000099\\\"><U>https://gluonhq.com/products/javafx/</U></FONT></HTML>");

        lowerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        specifyOjfxLabel.setText("Please browse JavaFX runtime directory");

        message.setText("    ");

        saveButton.setText("Save & Proceed");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lowerPanelLayout = new javax.swing.GroupLayout(lowerPanel);
        lowerPanel.setLayout(lowerPanelLayout);
        lowerPanelLayout.setHorizontalGroup(
            lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lowerPanelLayout.createSequentialGroup()
                        .addComponent(specifyOjfxLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerPanelLayout.createSequentialGroup()
                        .addGroup(lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileLocation)
                            .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(browseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        lowerPanelLayout.setVerticalGroup(
            lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(specifyOjfxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addGap(14, 14, 14)
                .addGroup(lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(message))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void linkClickedForOpenJFX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkClickedForOpenJFX
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI("https://openjfx.io/"));
            } catch (IOException | URISyntaxException e) {
                /* TODO: error handling */
            }
            /* TODO: error handling */ 
        } else {
            /* TODO: error handling */ 
        }
    }//GEN-LAST:event_linkClickedForOpenJFX

    


    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        performTextChange();
        String fileLocText = JFXAppLauncher.confirmJavaFXLocation(fileLocation.getText());
        JFXAppLauncher.setJavaFXLocation(fileLocText);
        this.setVisible(false);
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser chooser = new JFileChooser(); 
        String location = fileLocation.getText();
        File currentLocation = new File(location);
        chooser.setCurrentDirectory(currentLocation.exists()? currentLocation : new File("."));
        chooser.setDialogTitle("Select JavaFX directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
             fileLocation.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void performTextChange(){
        String fileLocText = JFXAppLauncher.confirmJavaFXLocation(fileLocation.getText());
        if (JFXAppLauncher.isValidJavaFXLocation(fileLocText)) {
            saveButton.setEnabled(true);
            message.setText("<HTML><FONT color=\"#009900\"> Save this settings and proceed to launch the application.</FONT></HTML>");
        } else {
            saveButton.setEnabled(false);
            message.setText("<HTML><FONT color=\"#990000\"> \"javafx.controls.jar\" and \"javafx.web.jar\" is not found in above directory</FONT></HTML>");
        }
    }
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JTextField fileLocation;
    private javax.swing.JLabel labelWithLink;
    private javax.swing.JLabel labelWithText;
    private javax.swing.JPanel lowerPanel;
    private javax.swing.JLabel message;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel specifyOjfxLabel;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
    

}
